export const AUTHORIZATION = 'Authorization'
export const LOGIN = 'Login'
export const LOADING = 'Loading'
export const AUTHENTICATED = 'AUTHENTICATED'
export const ERROR = 'ERROR'
export const FINISHED = 'FINISHED'
export const INITIALIZED = 'INITIALIZED'
